[package]
name = "rust-cpp-integration"
authors = ["Oliver With"]
version = "0.1.0"
edition = "2024"
build="build.rs"

[dependencies]
cxx = "1.0.158"

[build-dependencies]
cxx-build = "1.0.158"
cmake = "0.1.54"



[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
